### <font color = 'red'> Class 12

#### Sorting arrays using numpy

In [5]:
import numpy as np
import pandas as pd

In [9]:
x = np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
x = np.array([3,4,-3,0,8])
x

array([ 3,  4, -3,  0,  8])

In [13]:
np.sort(x)

array([-3,  0,  3,  4,  8])

In [21]:
# original array unchanged when using np.sort()
x

array([-3,  0,  3,  4,  8])

In [25]:
#if you want to sort the array in place in python it changes the original array
x.sort()
x

array([-3,  0,  3,  4,  8])

In [27]:
x = np.array([2,3,-2,7,0])
np.argsort(x)

array([2, 4, 0, 1, 3], dtype=int64)

##### Sorting along rows and column

In [37]:
rand = np.random.RandomState(42)
X = rand.randint(0,10,(4,6))
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [49]:
# axis = 0 is column
np.sort(X, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [53]:
# axis = 1 is row
np.sort(X, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [55]:
np.sort(X)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [65]:
# Partial Sorting
x = np.array([7,2,3,1,6,5,4])
print(x)
np.partition(x,3) # number greater than 3 goes to right of the array whereas smaller than 3 are on the left position of array

[7 2 3 1 6 5 4]


array([2, 1, 3, 4, 6, 5, 7])

In [69]:
-np.partition(-x,3) #negative partition

array([6, 7, 5, 4, 2, 3, 1])

#### Structured Data

In [82]:
name = ['Alice','Bob','Cathy','Steve']
age = [35,42,25,15]
weight = [60.3,80.2,75.1,51.0]

In [80]:
data = np.zeros(4,dtype = {'names':('name','age','weight'),
                           'formats' :('U10','i4','f8')
})
data.dtype

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [84]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [86]:
data['name'] = name
data['age'] = age
data['weight'] = weight
data

array([('Alice', 35, 60.3), ('Bob', 42, 80.2), ('Cathy', 25, 75.1),
       ('Steve', 15, 51. )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [88]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Steve'], dtype='<U10')

In [90]:
data[0]

('Alice', 35, 60.3)

In [92]:
data[0]['name'] = 'Michael'
data[0]

('Michael', 35, 60.3)

In [94]:
data[1]['age'] = 32
data[1]

('Bob', 32, 80.2)

In [96]:
data[data['age']<30]['name']

array(['Cathy', 'Steve'], dtype='<U10')