### <font color = 'red'> Class 8

In [2]:
!pip install numpy

In [4]:
import numpy as np

In [6]:
np.__version__

'1.26.4'

In [10]:
arr = np.array([2,4,8,16])
print(arr)
print(type(arr))

[ 2  4  8 16]
<class 'numpy.ndarray'>


In [20]:
np.array([1,2.4,3,5])

array([1. , 2.4, 3. , 5. ])

In [22]:
np.array([3,2.4,3,'myst'])

array(['3', '2.4', '3', 'myst'], dtype='<U32')

In [24]:
np.array([1.25,2,3,4],dtype='int16')

array([1, 2, 3, 4], dtype=int16)

In [26]:
np.array([1.25,2,3,4],dtype='float32')

array([1.25, 2.  , 3.  , 4.  ], dtype=float32)

In [36]:
# 2 d array 3x3 
np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Built in methods

In [41]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [49]:
x = np.ones((3,5,2),dtype = float)
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [51]:
x.size

30

In [53]:
x.shape

(3, 5, 2)

In [55]:
x.ndim

3

In [57]:
np.arange(1,31,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [63]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [65]:
np.random.random((3,3))

array([[0.55827945, 0.63193272, 0.05033331],
       [0.39167227, 0.92318611, 0.83424212],
       [0.99526374, 0.76017092, 0.86091978]])

In [82]:
# 3x3 random value array of normally distributed data with mean 0 and sd 1
np.random.normal(0,1,(3,3))

array([[ 0.76645025,  0.2749133 ,  1.36052069],
       [ 0.0237987 ,  0.54078239, -0.52403283],
       [-0.1742792 ,  1.39499083,  0.77721926]])

In [90]:
# 3x3 random int matrices from 1 to 9
np.random.randint(0,10,size=(3,3))

array([[6, 2, 5],
       [3, 9, 0],
       [6, 3, 4]])

In [92]:
# 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
# uninitialized array of 3 integers 
np.empty(10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])