## <font color = 'red'> Class 9

#### Arrays

In [4]:
import numpy as np

In [6]:
np.random.seed(0)

In [8]:
x1 = np.random.randint(10,size = 6)
x2 = np.random.randint(10,size = (4,3))
x3 = np.random.randint(10,size=(2,3,4))
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
print(x1.ndim)
print(x2.ndim)
print(x3.ndim)

1
2
3


In [16]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(6,)
(4, 3)
(2, 3, 4)


In [21]:
print(x1.size)
print(x2.size)
print(x3.size)

6
12
24


In [23]:
x1.dtype

dtype('int32')

In [25]:
print('x2 itemsize =',x2.itemsize )
print('x2 nbytes = ',x2.nbytes)

x2 itemsize = 4
x2 nbytes =  48


#### Array indexing

In [30]:
print(x1)
print(x1[0])

[5 0 3 3 7 9]
5


In [32]:
print(x2)
print(x2[0,0])
print(x2[2,-1])

[[3 5 2]
 [4 7 6]
 [8 8 1]
 [6 7 7]]
3
1


In [34]:
x2[2,-1] = 3.1415
print(x2)
print('updated item at row 3 and column 3 = ',x2[2,-1])

[[3 5 2]
 [4 7 6]
 [8 8 3]
 [6 7 7]]
updated item at row 3 and column 3 =  3


In [46]:
x2[3,1]

7

In [48]:
x2[3,1] = 9
x2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 3],
       [6, 9, 7]])

#### Array slicing

In [53]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
print('x[:7] = ',x[:7])
print('x[7:] = ',x[7:])
print('x[3:8] = ',x[3:8])
print('x[::2] = ',x[::2])
print('x[2::2] = ',x[2::2])
print('x[::] = ',x[::])

x[:7] =  [0 1 2 3 4 5 6]
x[7:] =  [7 8 9]
x[3:8] =  [3 4 5 6 7]
x[::2] =  [0 2 4 6 8]
x[2::2] =  [2 4 6 8]
x[::] =  [0 1 2 3 4 5 6 7 8 9]


In [65]:
#here step value is used to print the values in reverse from 7th to 4th element
print('x[7:3:-1] = ',x[7:3:-1])

x[7:3:-1] =  [7 6 5 4]


#### Multidimensional array

In [69]:
x2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 3],
       [6, 9, 7]])

In [83]:
#rows from 0 to 2 columns from 0 to 1
x2[:3,:2]

array([[3, 5],
       [4, 7],
       [8, 8]])

In [81]:
# every other row,all columns
x2[::2,:]

array([[3, 5, 2],
       [8, 8, 3]])

In [85]:
#reverse altogether
x2[::-1,::-1]

array([[7, 9, 6],
       [3, 8, 8],
       [6, 7, 4],
       [2, 5, 3]])

##### reshaping arrays

In [97]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
np.arange(1,17).reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [133]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [113]:
arr2d = ([
        [1,2,3],
        [4,5,6]
])
np.concatenate([arr2d,arr2d])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [121]:
# concatenate along second axis where axis = 1 is column
np.concatenate([arr2d,arr2d],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [125]:
np.vstack([x,arr2d])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [135]:
y = [[99],
     [99]]
np.hstack([y,arr2d])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])